const data = [
  { id: 1, item: "pizza", price: 140, type: "veg" },
  { id: 2, item: "chowmin", price: 100, type: "veg" },
  { id: 3, item: "burger", price: 120, type: "veg" },
  { id: 4, item: "pasta", price: 150, type: "veg" },
  { id: 5, item: "sandwich", price: 80, type: "veg" },
  { id: 6, item: "fries", price: 60, type: "veg" },
  { id: 7, item: "hot dog", price: 90, type: "nonveg" },
  { id: 8, item: "taco", price: 110, type: "veg" },
  { id: 9, item: "sushi", price: 200, type: "veg" },
  { id: 10, item: "burrito", price: 130, type: "nonveg" },
  { id: 11, item: "noodles", price: 110, type: "veg" },
  { id: 12, item: "fried rice", price: 100, type: "veg" },
  { id: 13, item: "steak", price: 250, type: "nonveg" },
  { id: 14, item: "salad", price: 70, type: "veg" },
  { id: 15, item: "chicken wings", price: 140, type: "veg" },
  { id: 16, item: "wrap", price: 90, type: "veg" },
  { id: 17, item: "omelette", price: 60, type: "nonveg" },
  { id: 18, item: "pancakes", price: 80, type: "veg" },
  { id: 19, item: "waffles", price: 90, type: "veg" },
  { id: 20, item: "crepes", price: 100, type: "veg" },
  { id: 21, item: "lasagna", price: 180, type: "veg" },
  { id: 22, item: "risotto", price: 150, type: "veg" },
  { id: 23, item: "ramen", price: 120, type: "veg" },
  { id: 24, item: "dumplings", price: 110, type: "veg" },
  { id: 25, item: "spring rolls", price: 90, type: "veg" },
  { id: 26, item: "nachos", price: 100, type: "nonveg" },
  { id: 27, item: "quesadilla", price: 130, type: "nonveg" },
  { id: 28, item: "curry", price: 160, type: "veg" },
  { id: 29, item: "tandoori chicken", price: 180, type: "nonveg" },
  { id: 30, item: "bbq ribs", price: 200, type: "nonveg" },
];

export default data;
